#!/bin/bash
#Update discord in Fedora script.
#Source documentation can be found at https://docs.fedoraproject.org/en-US/quick-docs/rpmfusion-setup/
#Author: Zachary Schmalz - SysEngIV

#Check if script is running with root permissions.
if [ "$EUID" -ne 0 ]
  then echo "Please run as root"
  exit
fi

#remove existing discord instance
if flatpak list | grep -q "discord"; then
    echo "Flatpak application 'discord' is installed. Removing it..."
    flatpak uninstall -y "discord"
    if [ $? -eq 0 ]; then
        echo "Successfully removed Discord."
    else
        echo "Failed to remove Discord."
    fi
else
    echo "Flatpak application Discord is not installed."
fi

#Add repos
dnf install \https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm -y
dnf install \https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm -y

#Install discord
dnf install discord -y
